version: "3.8"

services:
  app:
    build: .
    container_name: hotel-app
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
      temporal:
        condition: service_started
    environment:
      APP_URL: http://hotel-app:3000
      REDIS_URL: redis://redis:6379
      TEMPORAL_ADDRESS: temporal:7233
    restart: always

  redis:
    image: redis:7-alpine
    container_name: hotel-redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 2s
      retries: 5

  postgres:
    image: postgres:15
    container_name: temporal-postgres
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 5s
      timeout: 5s
      retries: 5

  temporal:
    image: temporalio/auto-setup:1.25
    container_name: temporal
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres
      - POSTGRES_DB=temporal
    ports:
      - "7233:7233"
    restart: always

volumes:
  pgdata: